### ISSUE TITLE
how to apply styling (control height and width) for autocomplete view?

### ISSUE THREAD

**Issue by harsha31** [TeamWertarbyte/material-ui-search-bar#20]

**Comment by leMaik** [comment]
Since our component internally uses the [AutoComplete component](http://www.material-ui.com/#/components/auto-complete) and passes all unknown props through, you can use `menuStyle` prop to customize the autocomplete menu style. You may get a _unknown prop 'menuStyle'_ warning, but you can ignore that.

**Comment by harsha31** [comment]
<SearchBar value = {this.state.searchKey}
                    style = {{"width":800}} 
                    onChange={(value) => {this.setState({searchKey:value})}}
                    onRequestSearch={this.onSearchRequest.bind(this)}
		    dataSource = {this.state.source}
		    menuStyle = {{width:200}}
/>.
It is not working for me.

**Comment by leMaik** [comment]
@harsha31 Try `popoverProps={{ style: { width: 200 } }}`, that might work.

**Comment by harsha31** [comment]
@leMaik Thanks. Working fine

**Comment by leMaik** [comment]
@harsha31 Great! You're welcome. :+1:
