### ISSUE TITLE
Recommended implementation for the actual search-string submission?

### ISSUE THREAD

**Issue by unprofessional** [TeamWertarbyte/material-ui-search-bar#68]
Stupid question: How should this actually be implemented? Is there something obvious I'm missing?

You have a Search Icon button, but it goes away when you type something into the input. The Search Icon button works, as can be determined by a `console.log` output in the `onRequestSearch` method, but it's being told to go `hidden` in the CSS when something is typed into the input. Instead, it's replaced by a `close` X icon button (which is actually because it becomes visible). Even your examples show this behavior.

So then we're left without a way to submit the value without hitting the return key. But what if I want to use this on mobile and still need that Search Icon button to be there?

Alternatively, what if I wanted to use React forms and add a Submit button (or just add a button in general) -- how can I make the default Search Icon button go away entirely so it doesn't confuse a user who might see it and think there are two "submit search" buttons?

I don't understand. Are we supposed to use the Search Icon button when something's typed into the input? If so, how do we keep the button from hiding itself?

**Comment by fllprbt** [comment]
Hey @unprofessional,

it's been a while since I last followed this repo but I 'd like to contrib at some point (I will discuss it with TeamWertarbyte). Truly the whole behaviour confused me as well... 

1) What I understand though from the api & examples is that the bar clearing behaviour (+ icon transitions and so on) is built-in the searchBar and you cannot opt-out (at least yet xD). Even if you use the api's `closeIcon` or `searchIcon` for your needs, you will confuse your user even more as he won't be knowing what the replaced 'X' will actually be doing...

2) Now, the `onRequestSearch` is triggered by the enter but not from the soft keyboards' "submit" buttons. **onKeyUp** this is fired: https://github.com/TeamWertarbyte/material-ui-search-bar/blob/62dcd1f3be0a3d5826eac59fff2fcb1af12c252b/src/components/SearchBar/SearchBar.js#L99-L108 The funny part is that the soft keyboards' submit buttons trigger the `e.charCode === 13 || e.key === 'Enter'` but I am afraid they don't fire the keyUp event.

To conclude
A quick remedy is to add another event which fires the `onRequestSearch` but for mobiles. I am willing to open a PR if we can proceed with this/there is another proposal.

**Comment by unprofessional** [comment]
@fllprbt , hey I really appreciate the detailed input. Ideally, I'd like there to be a submit button of some sort always there. It could just be a difference in UI/UX philosophy between what I'd like to see and what this component was designed for.

Either way, I ended up creating a simple custom component group using material's input and button, styled them up, and called it a day. Seemed easier than forking the repo and bringing all the overhead with it, anyway.

Closing this since I went another route. Thank you, though!
